In [1]:
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [2]:
type(a)

numpy.ndarray

In [7]:
# List of an Array
import numpy as np
b = np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
# List of an Array
import numpy as np
b = np.array([[5,5,5], [3,3,3], [6,6,6]])
b

array([[5, 5, 5],
       [3, 3, 3],
       [6, 6, 6]])

In [11]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
b = np.zeros(2)
b

array([0., 0.])

In [13]:
c = np.ones (3)
c

array([1., 1., 1.])

In [14]:
# Create an empty array with 2 elements 
d = np.empty(3)
d

array([1., 1., 1.])

---

In [16]:
# with range of elements 
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [17]:
# with specific range of elements
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
#continue...
g= np.arange(2, 20, 2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# linerly spaced arrays
h = np.linspace (0,10,num=5) #gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
# specific data types in array 
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [22]:
j= np.ones(3, dtype=np. float64)
j

array([1., 1., 1.])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# making and reshpaing a 3D array 
C = np.arange(24).reshape(2, 3, 4)
C

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])