# Numpy Practice Session

In [ ]:
# pip install numpy 

In [ ]:
# import this Library in j.notebook
import numpy as np

---

### Creating an array using numpy

In [3]:
import numpy as np

food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [13]:
price.mean()

5.0

In [14]:
# Zeros Method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
# Once Array Method
np.ones(2)

array([1., 1.])

In [16]:
# empty 
np.empty(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(2, 21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [23]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
np.arange(0, 51, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [26]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [30]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Array Functions

In [31]:
a = np.array([8,5,9,3,2,0,0.9,0.5])
a

array([8. , 5. , 9. , 3. , 2. , 0. , 0.9, 0.5])

In [32]:
a.sort()
a

array([0. , 0.5, 0.9, 2. , 3. , 5. , 8. , 9. ])

In [33]:
b = np.array([8,5,9,3,2,0,0.9,0.3])
b

array([8. , 5. , 9. , 3. , 2. , 0. , 0.9, 0.3])

In [34]:
c = np.concatenate((a,b))
c

array([0. , 0.5, 0.9, 2. , 3. , 5. , 8. , 9. , 8. , 5. , 9. , 3. , 2. ,
       0. , 0.9, 0.3])

In [35]:
c.sort()
c

array([0. , 0. , 0.3, 0.5, 0.9, 0.9, 2. , 2. , 3. , 3. , 5. , 5. , 8. ,
       8. , 9. , 9. ])

### 2D array

In [37]:
a = np.array([[1, 2, 3, 4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
b = np.array([[3,4,6,5], [3,5,8,5]])
b

array([[3, 4, 6, 5],
       [3, 5, 8, 5]])

In [46]:
c = np.concatenate((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 6, 5],
       [3, 5, 8, 5]])